# Generated by Django 4.2.3 on 2023-08-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='0', verbose_name='Цена'),
        ),
    ]
