# Generated by Django 4.2.3 on 2023-08-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_remove_productimage_product_product_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='magazine.productimage'),
        ),
    ]
