# Generated by Django 4.2.3 on 2023-08-14 09:00

from django.db import migrations, models
import django.db.models.deletion
import magazine.models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_alter_product_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
        migrations.AddField(
            model_name='productimage',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='magazine.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.ImageField(upload_to=magazine.models.get_image_filename, verbose_name='Изображение'),
        ),
    ]
