# Generated by Django 4.2.3 on 2023-08-18 10:49

from django.db import migrations, models
import django.db.models.deletion
import magazine.models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_remove_product_photos_productimage_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='lft',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='rght',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='tree_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='responce',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.comment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y-%m-%d/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.ImageField(upload_to=magazine.models.get_image_filename, verbose_name='Дополнительное Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='magazine.product'),
        ),
    ]
